CREATE TABLE `sys_role` (
  `id` bigint NOT NULL COMMENT '主键',
  `code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '例: ADMIN / OPS / USER',
  `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '角色中文名称',
  `dept_id` bigint unsigned DEFAULT NULL COMMENT '归属部门 ID',
  `extra_dept_ids` json DEFAULT NULL COMMENT '附加部门 ID 列表（JSON 数组）',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '1启用 0禁用',
  `data_scope` varchar(32) NOT NULL DEFAULT 'ALL' COMMENT 'ALL/DEPT/DEPT_AND_CHILD/SELF/CUSTOM',
  `data_scope_ext` json DEFAULT NULL COMMENT '扩展数据范围，CUSTOM 时存 JSON 数组',
  `remark` varchar(255) DEFAULT NULL,
  `sort_no` int NOT NULL DEFAULT '0' COMMENT '排序号，越小越前',
  `create_by` bigint DEFAULT NULL,
  `create_time` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_by` bigint DEFAULT NULL,
  `update_time` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '0正常 1删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_role_code` (`code`),
  KEY `idx_role_status` (`status`),
  KEY `idx_role_sort` (`sort_no`),
  KEY `idx_sys_role_dept_id` (`dept_id`),
  CONSTRAINT `chk_role_datascope` CHECK ((`data_scope` in (_utf8mb4'ALL',_utf8mb4'DEPT',_utf8mb4'DEPT_AND_CHILD',_utf8mb4'SELF',_utf8mb4'CUSTOM'))),
  CONSTRAINT `chk_role_status` CHECK ((`status` in (0,1)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='角色表\r\n';
