-- PostgreSQL 16 初始化脚本：xrcgs_roadsafety 巡查记录相关表
-- CREATE DATABASE xrcgs_roadsafety;
-- COMMENT ON DATABASE xrcgs_roadsafety IS 'XRCGS 路产安全业务数据库';

CREATE TABLE IF NOT EXISTS road_inspection_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_date DATE NOT NULL,
  unit_name VARCHAR(100) NOT NULL,
  weather VARCHAR(50),
  patrol_team VARCHAR(100),
  patrol_vehicle VARCHAR(100),
  location VARCHAR(255),
  inspection_content TEXT,
  issues_found TEXT,
  handling_situation_raw TEXT,
  handover_summary TEXT,
  remark TEXT,
  created_by VARCHAR(64),
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  exported_by VARCHAR(64),
  exported_at TIMESTAMP(6),
  export_file_name VARCHAR(255),
  approval_status VARCHAR(32) NOT NULL DEFAULT 'UNSUBMITTED',
  squad_code VARCHAR(64) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_record_date ON road_inspection_record(record_date);
CREATE INDEX IF NOT EXISTS idx_squad_code ON road_inspection_record(squad_code);
CREATE INDEX IF NOT EXISTS idx_created_by ON road_inspection_record(created_by);

COMMENT ON TABLE road_inspection_record IS '路产安全巡查记录主表';
COMMENT ON COLUMN road_inspection_record.id IS '主键 ID';
COMMENT ON COLUMN road_inspection_record.record_date IS '巡查日期';
COMMENT ON COLUMN road_inspection_record.unit_name IS '巡查单位名称';
COMMENT ON COLUMN road_inspection_record.weather IS '天气情况';
COMMENT ON COLUMN road_inspection_record.patrol_team IS '巡查人员或班组';
COMMENT ON COLUMN road_inspection_record.patrol_vehicle IS '巡查车辆';
COMMENT ON COLUMN road_inspection_record.location IS '巡查路线、里程与桩号';
COMMENT ON COLUMN road_inspection_record.inspection_content IS '巡查内容概述';
COMMENT ON COLUMN road_inspection_record.issues_found IS '发现问题描述';
COMMENT ON COLUMN road_inspection_record.handling_situation_raw IS '原始处理情况文本';
COMMENT ON COLUMN road_inspection_record.handover_summary IS '车辆装备案件交接情况';
COMMENT ON COLUMN road_inspection_record.remark IS '备注';
COMMENT ON COLUMN road_inspection_record.created_by IS '创建人';
COMMENT ON COLUMN road_inspection_record.created_at IS '创建时间';
COMMENT ON COLUMN road_inspection_record.updated_at IS '更新时间';
COMMENT ON COLUMN road_inspection_record.exported_by IS '导出人';
COMMENT ON COLUMN road_inspection_record.exported_at IS '导出时间';
COMMENT ON COLUMN road_inspection_record.export_file_name IS '导出文件名';
COMMENT ON COLUMN road_inspection_record.approval_status IS '审批状态';
COMMENT ON COLUMN road_inspection_record.squad_code IS '所属中队编码';

CREATE TABLE IF NOT EXISTS road_inspection_handling_detail (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_id BIGINT NOT NULL,
  category_code VARCHAR(50) NOT NULL,
  category_name VARCHAR(100) NOT NULL,
  detail_text TEXT NOT NULL,
  detail_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_handling_record FOREIGN KEY (record_id) REFERENCES road_inspection_record(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_record_category ON road_inspection_handling_detail(record_id, category_code);

COMMENT ON TABLE road_inspection_handling_detail IS '巡查记录处理分类明细表';
COMMENT ON COLUMN road_inspection_handling_detail.id IS '主键 ID';
COMMENT ON COLUMN road_inspection_handling_detail.record_id IS '巡查记录 ID';
COMMENT ON COLUMN road_inspection_handling_detail.category_code IS '处理分类编码';
COMMENT ON COLUMN road_inspection_handling_detail.category_name IS '处理分类名称';
COMMENT ON COLUMN road_inspection_handling_detail.detail_text IS '处理事项详情';
COMMENT ON COLUMN road_inspection_handling_detail.detail_order IS '排序号';
COMMENT ON COLUMN road_inspection_handling_detail.created_at IS '创建时间';

CREATE TABLE IF NOT EXISTS road_inspection_photo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_id BIGINT NOT NULL,
  file_id BIGINT NOT NULL,
  description VARCHAR(255),
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_photo_record FOREIGN KEY (record_id) REFERENCES road_inspection_record(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_record_sort ON road_inspection_photo(record_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_file_id ON road_inspection_photo(file_id);

COMMENT ON TABLE road_inspection_photo IS '巡查记录照片表';
COMMENT ON COLUMN road_inspection_photo.id IS '主键 ID';
COMMENT ON COLUMN road_inspection_photo.record_id IS '巡查记录 ID';
COMMENT ON COLUMN road_inspection_photo.file_id IS '文件 ID';
COMMENT ON COLUMN road_inspection_photo.description IS '图片说明';
COMMENT ON COLUMN road_inspection_photo.sort_order IS '排序号';
COMMENT ON COLUMN road_inspection_photo.created_at IS '创建时间';
