CREATE TABLE `sys_dept` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
  `parent_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT '父部门 ID，0 表示顶级',
  `path` varchar(512) COLLATE utf8mb4_general_ci NOT NULL COMMENT '物化路径 /1/3/5/，用于层级查询',
  `name` varchar(100) COLLATE utf8mb4_general_ci NOT NULL COMMENT '部门名称',
  `code` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '部门编码，选填',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态：1=启用，0=禁用',
  `sort_no` int NOT NULL DEFAULT '0' COMMENT '排序号，越小越靠前',
  `leader_user_id` bigint unsigned DEFAULT NULL COMMENT '负责人用户 ID',
  `phone` varchar(30) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '联系电话',
  `email` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '联系邮箱',
  `remark` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `create_by` bigint unsigned DEFAULT NULL COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint unsigned DEFAULT NULL COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除：0=在用，1=已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_dept_path` (`path`),
  UNIQUE KEY `uk_sys_dept_parent_name` (`parent_id`,`name`),
  KEY `idx_sys_dept_parent_id` (`parent_id`),
  KEY `idx_sys_dept_sort_no` (`parent_id`,`sort_no`),
  CONSTRAINT `chk_sys_dept_path_format` CHECK (regexp_like(`path`,_utf8mb4'^(/[0-9]+)+/$'))
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='系统部门';
