spring:
  profiles:
    include: local  # ⭐ 激活 dev 时，会额外加载 application-local.yml
  datasource:
    url: jdbc:mysql://localhost:3306/xrcgs_admin?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: ${DB_USER}
    password: ${DB_PASS}

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: ${RD_PASS}

syslog:
  enabled: true
  maxBodyLength: 2048
  logResult: false
  cleanup:
    enabled: true
    #暂时按开发环境来，等稳定或有法律风险后开启180天，5000条批删除
    retention-days: 30
    cron: 0 30 3 * * ?
    batch-size: 500 # 或者 5000，取决于你的数据量